#!/usr/bin/env perl

use Mojolicious::Lite -signatures;

=pod
Under
Authentication and code shared between multiple routes can be realized easily with routes generated by "under" in 
Mojolicious::Lite. All following routes are only evaluated if the callback returned a true value.
=cut

# Tambien se puede relacionar grupos de route con la palabra clave "group" en Mojolicious::Lite, el cual permite el 
# anidamiento de routes generadas con "under" en Mojolicious::lite.

# Global logic shared by all routes
under sub ($c){
  return 1 if $c->req->headers->header('X-Bender');
  $c->render(text => "You are not Bender.");
  return undef;
};

# Admin section
group {
  
  # Local logic shared only by routes in this group
  under '/admin' => sub ($c) { # Under only affects routes of this group
    print "ENTRO\n";
    return 1 if $c->req->headers->header('X-Awesome'); #Pass validation
    $c->render(text => "You're not awesome enough."); # No pass validation
    return undef;
  };
  # GET /admin/dashboard
  get '/dashboard' => {text => 'Nothing to see here yet.'}; # Text to show if it pass validation
  # Si bien te permite hacer peticion GET a esta parte, nunca se llega, ya que no pasamos la primera validacion del 
  #   under general, por lo mismo al realizar el Request no imprimer el mensaje "ENTRO"
};

# GET /welcome
get '/welcome' => {text => 'Hi Bender.'}; # Use "under" outsite from "group", show text if pass logical authentication

app->start;