#!/usr/bin/env perl

use Mojolicious::Lite -signatures;

=pod
Under
Authentication and code shared between multiple routes can be realized easily with routes generated by "under" in 
Mojolicious::Lite. All following routes are only evaluated if the callback returned a true value.

TEST
  morbo ./under_2.pl
=cut

# Prefixing multiple routes is another good use for it 
# Otro buen uso es el anteponer multiples routes


# /foo
under '/foo'; # This route alone gives you error

# /foo/bar
get '/bar' => {text => 'foo bar'};

# /foo/baz
get '/baz' => {text => 'foo baz'};

# / (reset)
under '/' => {msg => 'whatever'}; # This route alone gives you error

# /bar
get '/bar' => {inline => '<%= $msg %> works'}; # $msg from above line

app->start;