#!/usr/bin/env perl

use Mojolicious::Lite -signatures;

=pod
Under
Authentication and code shared between multiple routes can be realized easily with routes generated by "under" in 
Mojolicious::Lite. All following routes are only evaluated if the callback returned a true value.

TEST
  morbo ./under_1.pl
=cut

# Authenticate based on name parameter
under sub ($c) {
  # Authenticated
  my $name = $c->param('name') || '';
  return 1 if ($name eq "Bender"); # Continue to index

  # No Authenticated
  $c->render(template => "denied"); # Use denied template
};

# Only reached when authenticated (Solo lleha a "index" al pasar autentificacion de under)
get '/' => 'index';

app->start;
__DATA__

@@ denied.html.ep
You are not Bender, permission denied.

@@ index.html.ep
Hi Bender