#!/usr/bin/env perl

use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;
use FindBin;
use File::Spec ();
use Cwd ();
#use Portal ();

 # Ejemplos de rutas en proyecto
 print "Esto encontre ========> ", curfile->dirname->sibling('lib')->to_string,"\n";
 print "Esto es de FINDBIN ====> ","$FindBin::Bin/","\n";
 print "Esto es de FINDBIN 2 ====> ","$FindBin::Bin/../lib","\n";
 my @directorio_partes = File::Spec->splitdir($FindBin::Bin);
 #my @directorio_partes = File::Spec->splitdir(Cwd::getcwd);
 print "Esto es de FINDBIN DIRECTORIOS ====> ","@directorio_partes","\n";
 my $path_completo = File::Spec->catdir(@directorio_partes);
 print "Esto es de FINDBIN DIRECTORIOS path ====> ","$path_completo","\n";
 my $retroceso_dos_directorios = Cwd::abs_path(File::Spec->catdir($path_completo,'../..'));
 print "Esto es de FINDBIN DIRECTORIOS path ../.. ====> ","$retroceso_dos_directorios","\n";
 # OUTPUT
 #    Esto encontre ========> /home/salomon/Documents/Cursos/Mojolicious/growing/my_app/lib
 #    Esto es de FINDBIN ====> /home/salomon/Documents/Cursos/Mojolicious/growing/my_app/script
 #    Esto es de FINDBIN 2 ====> /home/salomon/Documents/Cursos/Mojolicious/growing/my_app/script/../lib

# Start command line interface for application
Mojolicious::Commands->start_app('MyApp'); # Inicia con /lib/MyApp.pm
